package com.magicBook.cms.domain;

import java.io.Serializable;

public class Deity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_deity.id
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_deity.major
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_deity.cell
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    private Integer cell;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_deity.type
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exam_deity
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_deity.id
     *
     * @return the value of exam_deity.id
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_deity.id
     *
     * @param id the value for exam_deity.id
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_deity.major
     *
     * @return the value of exam_deity.major
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_deity.major
     *
     * @param major the value for exam_deity.major
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_deity.cell
     *
     * @return the value of exam_deity.cell
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public Integer getCell() {
        return cell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_deity.cell
     *
     * @param cell the value for exam_deity.cell
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public void setCell(Integer cell) {
        this.cell = cell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_deity.type
     *
     * @return the value of exam_deity.type
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_deity.type
     *
     * @param type the value for exam_deity.type
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_deity
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", major=").append(major);
        sb.append(", cell=").append(cell);
        sb.append(", type=").append(type);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}