package com.magicBook.cms.domain;

import java.io.Serializable;

public class DeityWithBLOBs extends Deity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_deity.problem
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    private String problem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_deity.answers
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    private String answers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_deity.optiona
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    private String optiona;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_deity.optionb
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    private String optionb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_deity.optionc
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    private String optionc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_deity.optiond
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    private String optiond;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_deity.optione
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    private String optione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_deity.optionf
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    private String optionf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_deity.optiong
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    private String optiong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_deity.optionh
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    private String optionh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_deity.introduce
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exam_deity
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_deity.problem
     *
     * @return the value of exam_deity.problem
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public String getProblem() {
        return problem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_deity.problem
     *
     * @param problem the value for exam_deity.problem
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public void setProblem(String problem) {
        this.problem = problem == null ? null : problem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_deity.answers
     *
     * @return the value of exam_deity.answers
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public String getAnswers() {
        return answers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_deity.answers
     *
     * @param answers the value for exam_deity.answers
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public void setAnswers(String answers) {
        this.answers = answers == null ? null : answers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_deity.optiona
     *
     * @return the value of exam_deity.optiona
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public String getOptiona() {
        return optiona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_deity.optiona
     *
     * @param optiona the value for exam_deity.optiona
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public void setOptiona(String optiona) {
        this.optiona = optiona == null ? null : optiona.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_deity.optionb
     *
     * @return the value of exam_deity.optionb
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public String getOptionb() {
        return optionb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_deity.optionb
     *
     * @param optionb the value for exam_deity.optionb
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public void setOptionb(String optionb) {
        this.optionb = optionb == null ? null : optionb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_deity.optionc
     *
     * @return the value of exam_deity.optionc
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public String getOptionc() {
        return optionc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_deity.optionc
     *
     * @param optionc the value for exam_deity.optionc
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public void setOptionc(String optionc) {
        this.optionc = optionc == null ? null : optionc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_deity.optiond
     *
     * @return the value of exam_deity.optiond
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public String getOptiond() {
        return optiond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_deity.optiond
     *
     * @param optiond the value for exam_deity.optiond
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public void setOptiond(String optiond) {
        this.optiond = optiond == null ? null : optiond.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_deity.optione
     *
     * @return the value of exam_deity.optione
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public String getOptione() {
        return optione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_deity.optione
     *
     * @param optione the value for exam_deity.optione
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public void setOptione(String optione) {
        this.optione = optione == null ? null : optione.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_deity.optionf
     *
     * @return the value of exam_deity.optionf
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public String getOptionf() {
        return optionf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_deity.optionf
     *
     * @param optionf the value for exam_deity.optionf
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public void setOptionf(String optionf) {
        this.optionf = optionf == null ? null : optionf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_deity.optiong
     *
     * @return the value of exam_deity.optiong
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public String getOptiong() {
        return optiong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_deity.optiong
     *
     * @param optiong the value for exam_deity.optiong
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public void setOptiong(String optiong) {
        this.optiong = optiong == null ? null : optiong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_deity.optionh
     *
     * @return the value of exam_deity.optionh
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public String getOptionh() {
        return optionh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_deity.optionh
     *
     * @param optionh the value for exam_deity.optionh
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public void setOptionh(String optionh) {
        this.optionh = optionh == null ? null : optionh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_deity.introduce
     *
     * @return the value of exam_deity.introduce
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_deity.introduce
     *
     * @param introduce the value for exam_deity.introduce
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_deity
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", problem=").append(problem);
        sb.append(", answers=").append(answers);
        sb.append(", optiona=").append(optiona);
        sb.append(", optionb=").append(optionb);
        sb.append(", optionc=").append(optionc);
        sb.append(", optiond=").append(optiond);
        sb.append(", optione=").append(optione);
        sb.append(", optionf=").append(optionf);
        sb.append(", optiong=").append(optiong);
        sb.append(", optionh=").append(optionh);
        sb.append(", introduce=").append(introduce);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}