package com.magicBook.cms.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.magicBook.cms.domain.Deity;
import com.magicBook.cms.domain.DeityExample;
import com.magicBook.cms.domain.DeityWithBLOBs;

public interface DeityMapper {
	
	
	@Select("select * from exam_deity where problem like '%${problem}%' and type = #{type}")
	List<Map> selectLikeProblem(@Param("problem")String problem,@Param("type")String type);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_deity
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    long countByExample(DeityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_deity
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    int deleteByExample(DeityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_deity
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_deity
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    int insert(DeityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_deity
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    int insertSelective(DeityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_deity
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    List<DeityWithBLOBs> selectByExampleWithBLOBs(DeityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_deity
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    List<Deity> selectByExample(DeityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_deity
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    DeityWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_deity
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") DeityWithBLOBs record, @Param("example") DeityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_deity
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") DeityWithBLOBs record, @Param("example") DeityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_deity
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    int updateByExample(@Param("record") Deity record, @Param("example") DeityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_deity
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    int updateByPrimaryKeySelective(DeityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_deity
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(DeityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_deity
     *
     * @mbg.generated Mon Jun 10 20:13:40 CST 2019
     */
    int updateByPrimaryKey(Deity record);
}